w="123456hjghg-"
# n=w.lower()
# print(n)
# m=w.upper()
# print(m)
# o=w.title()
# print(o)
# p=w.capitalize()
# print(p)
# print(w.find('e',4))
# print(w.index('e',4))
print(w.isalpha())
print(w.isdigit())
print(w.isalnum())